# keep in sync with versions in [tool.poetry.group.dev.dependencies]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.3.5
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.9.0
    hooks:
      - id: mypy
        language: system
        pass_filenames: false
        args: [ "." ]
  # TODO doesn't work; fix it
#  - repo: https://github.com/RobertCraigie/pyright-python
#    rev: v1.1.357
#    hooks:
#      - id: pyright
#        args: [ "--project", ".pyrightconfig.json" ]
